// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: pkg/grpc/userapi.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserapiClient is the client API for Userapi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserapiClient interface {
	GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserReply, error)
	GetUsers(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (Userapi_GetUsersClient, error)
	PostUser(ctx context.Context, in *UserPost, opts ...grpc.CallOption) (*UserReply, error)
	PutUser(ctx context.Context, in *UserPut, opts ...grpc.CallOption) (*UserReply, error)
	DeleteUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserReply, error)
}

type userapiClient struct {
	cc grpc.ClientConnInterface
}

func NewUserapiClient(cc grpc.ClientConnInterface) UserapiClient {
	return &userapiClient{cc}
}

func (c *userapiClient) GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserReply, error) {
	out := new(UserReply)
	err := c.cc.Invoke(ctx, "/grpc.Userapi/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userapiClient) GetUsers(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (Userapi_GetUsersClient, error) {
	stream, err := c.cc.NewStream(ctx, &Userapi_ServiceDesc.Streams[0], "/grpc.Userapi/GetUsers", opts...)
	if err != nil {
		return nil, err
	}
	x := &userapiGetUsersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Userapi_GetUsersClient interface {
	Recv() (*UserReply, error)
	grpc.ClientStream
}

type userapiGetUsersClient struct {
	grpc.ClientStream
}

func (x *userapiGetUsersClient) Recv() (*UserReply, error) {
	m := new(UserReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userapiClient) PostUser(ctx context.Context, in *UserPost, opts ...grpc.CallOption) (*UserReply, error) {
	out := new(UserReply)
	err := c.cc.Invoke(ctx, "/grpc.Userapi/PostUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userapiClient) PutUser(ctx context.Context, in *UserPut, opts ...grpc.CallOption) (*UserReply, error) {
	out := new(UserReply)
	err := c.cc.Invoke(ctx, "/grpc.Userapi/PutUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userapiClient) DeleteUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserReply, error) {
	out := new(UserReply)
	err := c.cc.Invoke(ctx, "/grpc.Userapi/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserapiServer is the server API for Userapi service.
// All implementations must embed UnimplementedUserapiServer
// for forward compatibility
type UserapiServer interface {
	GetUser(context.Context, *UserRequest) (*UserReply, error)
	GetUsers(*UserRequest, Userapi_GetUsersServer) error
	PostUser(context.Context, *UserPost) (*UserReply, error)
	PutUser(context.Context, *UserPut) (*UserReply, error)
	DeleteUser(context.Context, *UserRequest) (*UserReply, error)
	mustEmbedUnimplementedUserapiServer()
}

// UnimplementedUserapiServer must be embedded to have forward compatible implementations.
type UnimplementedUserapiServer struct {
}

func (UnimplementedUserapiServer) GetUser(context.Context, *UserRequest) (*UserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserapiServer) GetUsers(*UserRequest, Userapi_GetUsersServer) error {
	return status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedUserapiServer) PostUser(context.Context, *UserPost) (*UserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostUser not implemented")
}
func (UnimplementedUserapiServer) PutUser(context.Context, *UserPut) (*UserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutUser not implemented")
}
func (UnimplementedUserapiServer) DeleteUser(context.Context, *UserRequest) (*UserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedUserapiServer) mustEmbedUnimplementedUserapiServer() {}

// UnsafeUserapiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserapiServer will
// result in compilation errors.
type UnsafeUserapiServer interface {
	mustEmbedUnimplementedUserapiServer()
}

func RegisterUserapiServer(s grpc.ServiceRegistrar, srv UserapiServer) {
	s.RegisterService(&Userapi_ServiceDesc, srv)
}

func _Userapi_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserapiServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Userapi/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserapiServer).GetUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Userapi_GetUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserapiServer).GetUsers(m, &userapiGetUsersServer{stream})
}

type Userapi_GetUsersServer interface {
	Send(*UserReply) error
	grpc.ServerStream
}

type userapiGetUsersServer struct {
	grpc.ServerStream
}

func (x *userapiGetUsersServer) Send(m *UserReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Userapi_PostUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPost)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserapiServer).PostUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Userapi/PostUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserapiServer).PostUser(ctx, req.(*UserPost))
	}
	return interceptor(ctx, in, info, handler)
}

func _Userapi_PutUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPut)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserapiServer).PutUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Userapi/PutUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserapiServer).PutUser(ctx, req.(*UserPut))
	}
	return interceptor(ctx, in, info, handler)
}

func _Userapi_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserapiServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Userapi/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserapiServer).DeleteUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Userapi_ServiceDesc is the grpc.ServiceDesc for Userapi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Userapi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Userapi",
	HandlerType: (*UserapiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _Userapi_GetUser_Handler,
		},
		{
			MethodName: "PostUser",
			Handler:    _Userapi_PostUser_Handler,
		},
		{
			MethodName: "PutUser",
			Handler:    _Userapi_PutUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _Userapi_DeleteUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetUsers",
			Handler:       _Userapi_GetUsers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/grpc/userapi.proto",
}
